//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task5.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task5.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправленный код Хэмминга.
        /// </summary>
        public static string CorrectedHammingCodeLabelText {
            get {
                return ResourceManager.GetString("CorrectedHammingCodeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиции ошибок.
        /// </summary>
        public static string ErrorPositionsLabelText {
            get {
                return ResourceManager.GetString("ErrorPositionsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синдром ошибки.
        /// </summary>
        public static string ErrorSyndromeLabelText {
            get {
                return ResourceManager.GetString("ErrorSyndromeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код Хэмминга.
        /// </summary>
        public static string HammingCodeLabelText {
            get {
                return ResourceManager.GetString("HammingCodeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код Хэмминга с ошибками.
        /// </summary>
        public static string HammingCodeWithErrorsLabelText {
            get {
                return ResourceManager.GetString("HammingCodeWithErrorsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник Информации.
        /// </summary>
        public static string InformationSourceComponentLabelText {
            get {
                return ResourceManager.GetString("InformationSourceComponentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string MessageLabelText {
            get {
                return ResourceManager.GetString("MessageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрядов.
        /// </summary>
        public static string NumberOfDigitsTextBoxWatermark {
            get {
                return ResourceManager.GetString("NumberOfDigitsTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ошибок.
        /// </summary>
        public static string NumberOfErrorsLabelText {
            get {
                return ResourceManager.GetString("NumberOfErrorsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщений.
        /// </summary>
        public static string NumberOfMessagesTextBoxWatermark {
            get {
                return ResourceManager.GetString("NumberOfMessagesTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверочных битов.
        /// </summary>
        public static string NumberOfParityBitsLabelText {
            get {
                return ResourceManager.GetString("NumberOfParityBitsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемник.
        /// </summary>
        public static string ReceiverComponentLabelText {
            get {
                return ResourceManager.GetString("ReceiverComponentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передатчик.
        /// </summary>
        public static string SenderComponentLabelText {
            get {
                return ResourceManager.GetString("SenderComponentLabelText", resourceCulture);
            }
        }
    }
}
